version: '3.3'
services:
  mosquitto:
      user: "1883:1883"
      image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      restart: unless-stopped
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./podman-compose/broker/mosquitto/log:/mosquitto/log
        - ./podman-compose/broker/mosquitto/config:/mosquitto/config
        - ./podman-compose/broker/mosquitto/data:/mosquitto/data
  intelligent-train-app:
    platform: linux/arm64/v8
    image: https://quay.io/repository/demo-ai-edge-crazy-train/intelligent-train:latest
    volumes:
      - /tmp:/tmp
    environment:
      - MQTT_BROKER=localhost
      - MQTT_PORT=1883
      - MQTT_TOPIC=train-image
      - MQTT_PUB_TOPIC=results
    depends_on:
      - mosquitto
 
  train-capture-image-app:
    platform: linux/arm64/v8
    image: quay.io/nmasse_itix/capture-image-arm64:latest
    ports:
      - 8080:8080
    environment: 
      - VIDEO_DEVICE_INDEX=0
      - TMP_FOLDER=/tmp
      - INTERVAL=1000
      - BROKER=tcp://localhost:1883
      - TOPIC=train-image
    volumes:
      - /dev:/dev
      - /tmp/crazy-images:/tmp/crazy-images
    depends_on:
      - mosquitto
      - intelligent-train-app
