version: '3.3'
networks:
  internal:
services:
  mosquitto:
      user: "1883:1883"
      image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      restart: unless-stopped
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./podman-compose/broker/mosquitto/log:/mosquitto/log
        - ./podman-compose/broker/mosquitto/config:/mosquitto/config
        - ./podman-compose/broker/mosquitto/data:/mosquitto/data
      networks:
        - internal
